// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Kmd.Logic.CitizenDocuments.Client.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class CitizenDocumentProviderConfigResponse
    {
        /// <summary>
        /// Initializes a new instance of the
        /// CitizenDocumentProviderConfigResponse class.
        /// </summary>
        public CitizenDocumentProviderConfigResponse()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the
        /// CitizenDocumentProviderConfigResponse class.
        /// </summary>
        public CitizenDocumentProviderConfigResponse(System.Guid? configurationId = default(System.Guid?))
        {
            ConfigurationId = configurationId;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "configurationId")]
        public System.Guid? ConfigurationId { get; set; }

    }
}
